# Generated by Django 6.0.6 on 2026-07-05 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descriprion',
            new_name='description',
        ),
    ]
